.catalog:
  name: "solodev"
  version: "v8.4.2"
  description: "A recommended stack for the MySQL RDBMS."
  uuid: solodev-0
  minimum_rancher_version: v1.0.0
  questions:
    - variable: SOLODEV_USER
      description: "Creates the main Admin Solodev User."
      label: "Solodev User"
      default: solodev
      required: true
      type: "string"
    - variable: SOLODEV_PASSWORD
      description: "A password for the main Solodev Admin User."
      default: password
      label: "Solodev Password"
      required: true
      type: password
    - variable: MYSQL_ROOT_PASSWORD
      description: "The password that will be set for the MySQL root superuser account."
      label: "MySQL Root Password"
      required: true
      default: password
      type: password
    - variable: MYSQL_DATABASE
      description: "Specify the name of a database to be created on image startup."
      label: "MySQL Database"
      required: true
      default: solodev
      type: "string"
    - variable: MYSQL_USER
      description: "Creates an additional MySQL (super)user. MySQL Password must also be set."
      label: "MySQL User"
      default: solodev
      required: true
      type: "string"
    - variable: MYSQL_PASSWORD
      description: "A password for the additional MySQL (super)user. MySQL User must also be set."
      label: "MySQL Password"
      default: password
      required: true
      type: password

  rancher-lb:
    scale: 1
    lb_config:
      certs: []
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: null
      unhealthy_threshold: 3

  php-fpm:
    scale: 2

  apache2:
    labels: 
      rap.host: '{STACK_NAME}.awspress.com'
    scale: 2

  mysql:
    scale: 1
