version: '2'

services:
  jenkins-slave:
    environment:
      JENKINS_USERNAME: jenkins
      JENKINS_PASSWORD: jenkins
      JENKINS_MASTER: http://jenkins-master:8080
    labels:
      io.rancher.scheduler.affinity:host_label: profile=jenkins
    tty: true
    image: techtraits/jenkins-slave
    links:
    - jenkins-master:jenkins-master
    privileged: true
    volumes:
    - /var/jenkins
    stdin_open: true
  jenkins-master:
    restart: 'no'
    labels:
      io.rancher.scheduler.affinity:host_label: jenkins-master=true
    tty: true
    image: techtraits/jenkins-master
    privileged: true
    stdin_open: true
    volume_driver: /var/jenkins_home
  jenkins-lb:
    ports:
      - 80:8080
    tty: true
    image: rancher/load-balancer-service
    links:
    - jenkins-master:jenkins-master
    stdin_open: true