.catalog:
  name: "Spacemade CI"
  version: "v0.0.1"
  description: "CI platform using Docker"
  uuid: spacemade-ci-0
  minimum_rancher_version: v1.5.0


version: '2'
services:
  jenkins-lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: tcp
        service: jenkins-master
        source_port: 8080
        target_port: 8080
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      interval: 2000
      strategy: recreate
