.catalog:
  name: "solodev-wxp"
  version: "v10.0.1"
  description: "Hosting Stack for Solodev WXP."
  uuid: solodev-wxp-0
  minimum_rancher_version: v1.0.0
  questions:
    - variable: APP_ENV
      description: ""
      label: "Environment"
      default: prod
      required: true
      type: enum   
      options:
        - dev
        - prod
    - variable: APP_BRANCH
      description: "What branch."
      label: "Branch"
      default: "develop"
      required: true
      type: enum   
      options:
        - develop
        - latest
    - variable: SOLODEV_PORT
      description: "Port for Solodev Admin."
      label: "Solodev Port"
      required: true
      type: "int"
      default: 121
    - variable: SOLODEV_USER
      description: "Creates the main Admin Solodev User."
      label: "Solodev User"
      default: solodev
      required: true
      type: "string"
    - variable: SOLODEV_PASSWORD
      description: "A password for the main Solodev Admin User."
      default: password
      label: "Solodev Password"
      required: true
      type: password
    - variable: MYSQL_ROOT_PASSWORD
      description: "The password that will be set for the MySQL root superuser account."
      label: "MySQL Root Password"
      required: true
      default: password
      type: password
    - variable: MYSQL_DATABASE
      description: "Specify the name of a database to be created on image startup."
      label: "MySQL Database"
      required: true
      default: solodev
      type: "string"
    - variable: MYSQL_USER
      description: "Creates an additional MySQL (super)user. MySQL Password must also be set."
      label: "MySQL User"
      default: solodev
      required: true
      type: "string"
    - variable: MYSQL_PASSWORD
      description: "A password for the additional MySQL (super)user. MySQL User must also be set."
      label: "MySQL Password"
      default: password
      required: true
      type: password
    - variable: MYSQL_PORT
      description: "Public port for access to MySQL through the load balancer"
      label: "MySQL Public LB Port"
      required: true
      default: 3306
      type: "int"
    - variable: APP_SECRET
      description: "A secret key for encryption."
      label: "App Secret"
      default: c5d3adbb98f43d650d12f0cc8fbcd7f8
      required: true
      type: password

php-fpm-lb:
  scale: 1
  labels:
    io.rancher.container.agent.role: environmentAdmin,agent
    io.rancher.container.agent_service.drain_provider: 'true'
    io.rancher.container.create_agent: 'true'
    io.rancher.lb_service.target: 'prefer-local'
  health_check:
    response_timeout: 2000
    healthy_threshold: 2
    port: 42
    unhealthy_threshold: 3
  start_on_create: true

php-fpm:
  scale: 1
  start_on_create: true
  labels:
    software: wxp
    branch: ${APP_BRANCH}

nginx-lb:
  scale: 1
  labels:
    io.rancher.container.agent.role: environmentAdmin,agent
    io.rancher.container.agent_service.drain_provider: 'true'
    io.rancher.container.create_agent: 'true'
    io.rancher.lb_service.target: 'prefer-local'
    rap.host: '{{ .Stack.Name }}.spce.io=>http:${SOLODEV_PORT}'
    rap.port: ${SOLODEV_PORT}
  lb_config:
    certs: []
    port_rules:
    - protocol: http
      service: nginx
      source_port: ${SOLODEV_PORT}
      target_port: 80
  health_check:
    response_timeout: 2000
    healthy_threshold: 2
    port: 42
    unhealthy_threshold: 3
  start_on_create: true

nginx:
  scale: 1
  labels:
    software: wxp-nginx
    branch: ${APP_BRANCH}
  start_on_create: true
  health_check:
      port: 80
      interval: 5000
      unhealthy_threshold: 3
      request_line: 'GET / HTTP/1.0'
      healthy_threshold: 2
      response_timeout: 5000

react-lb:
  scale: 1
  labels:
    io.rancher.container.agent.role: environmentAdmin,agent
    io.rancher.container.agent_service.drain_provider: 'true'
    io.rancher.container.create_agent: 'true'
    io.rancher.lb_service.target: 'prefer-local'
  health_check:
    response_timeout: 2000
    healthy_threshold: 2
    port: 42
    unhealthy_threshold: 3
  start_on_create: true

react:
  scale: 1
  labels:
    software: wxp-react
    branch: ${APP_BRANCH}
  start_on_create: true
  health_check:
    port: 3000
    interval: 5000
    unhealthy_threshold: 3
    request_line: 'GET / HTTP/1.0'
    healthy_threshold: 2
    response_timeout: 5000

mysql:
  scale: 1
  start_on_create: true
  health_check:
    healthy_threshold: 2
    response_timeout: 2000
    port: 3306
    unhealthy_threshold: 3
    interval: 2000
    strategy: recreate