name: Rancher Container Cron
description: |
  Rancher Container Crontab starts, stops or restarts containers 
version: v0.4.0
category: Framework
labels:
  io.rancher.orchestration.supported: 'cattle'
