Description: >
    This template deploys a CodeBuild Project to manage Rancher/RKE lifecycle events

Parameters:

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  VPC:
    Type: AWS::EC2::VPC::Id
    Description: Choose which VPC the Application Load Balancer should be deployed to

  Subnets:
    Description: Choose which subnets Codebuild should be deployed to
    Type: String

  LoadBalancerSecurityGroup:
    Description: Select the Load Balancer Security Group to use for the cluster hosts
    Type: AWS::EC2::SecurityGroup::Id

  AutoScalingGroup:
    Description: The AutoScalingGroup that the EC2 cluster is deployed to
    Type: String

  RancherBucket:
    Type: String
    Description: A reference to the S3 bucket for rke

  FQDN:
    Type: String
    Description: A reference to the FQDN

  InstanceUser:
    Type: String
    Description: A reference to the InstanceUser
    
  Status:
    Type: String
    Default: ''
    Description: A reference to the Status

  CodeBuildProjectName:
    Type: String
    Description: Name of codebuild project used for running rke

Resources:

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref CodeBuildProjectName
      ServiceRole: !Ref CodeBuildRole
      Artifacts:
        Type: S3
        EncryptionDisabled: True
        OverrideArtifactName: True
        Location: !Ref 'RancherBucket'
        Name: 'codebuild'
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: docker.io/techcto/python-codebuild
        EnvironmentVariables:
          - Name: CLUSTER
            Value: !Ref AutoScalingGroup
            Type: PLAINTEXT
          - Name: FQDN
            Value: !Ref FQDN
            Type: PLAINTEXT
          - Name: InstanceUser
            Value: !Ref InstanceUser
            Type: PLAINTEXT
          - Name: Status
            Value: !Ref Status
            Type: PLAINTEXT
          - Name: Bucket
            Value: !Ref RancherBucket
            Type: PLAINTEXT
      TimeoutInMinutes: 20
      # VpcConfig:
      #   VpcId: !Ref VPC
      #   Subnets: [!Ref Subnets]
      #   SecurityGroupIds: [!Ref LoadBalancerSecurityGroup]
      Source:
        Location: 'https://github.com/techcto/rke-runner'
        Type: GITHUB

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - 'logs:*'
                - 'autoscaling:CompleteLifecycleAction'
                - 'autoscaling:DescribeAutoScalingInstances'
                - 'ec2:CreateNetworkInterface'
                - 'ec2:DescribeInstances'
                - 'ec2:DescribeInstanceAttribute'
                - 'ec2:DescribeInstanceStatus'
                - 'ec2:DescribeHosts'
                - 'ec2:DescribeNetworkInterfaces'
                - 'ec2:DeleteNetworkInterface'
                - 'ec2:DescribeSubnets'
                - 'ec2:DescribeSecurityGroups'
                - 'ec2:DescribeDhcpOptions'
                - 'ec2:DescribeVpcs'
                - 'ec2:CreateNetworkInterfacePermission'
                - 'sns:Publish'
                - 'sns:ListSubscriptions'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 's3:*'
                Resource: !Join ['', ['arn:aws:s3:::', !Ref 'RancherBucket', /*]]