name: Docker Rancher Proxy
description: "Automatic Proxy for Rancher with Let's Encrypt support"
version: "v0.0.1"
category: Networking
maintainer: TechCTO
license: MIT
projectURl: "https://github.com/techcto/docker/rancher-proxy"